---
# role: ansible-role-vscode
# file: molecule/all/molecule.yml

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/shared/yamllint.yml
platforms:
  - name: vscode-amazon
    image: "jomrr/amazon-molecule:latest"
    command: ~
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: vscode-arch
    image: "jomrr/arch-molecule:latest"
    command: ~
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: vscode-centos7
    image: "jomrr/centos-molecule:7"
    command: ~
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: vscode-centos8
    image: "jomrr/centos-molecule:8"
    command: ~
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: vscode-debian9
    image: "jomrr/debian-molecule:9"
    command: ~
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: vscode-debian10
    image: "jomrr/debian-molecule:10"
    command: ~
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: vscode-debian
    image: "jomrr/debian-molecule:latest"
    command: ~
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: vscode-suse15
    image: "jomrr/suse-molecule:15"
    command: ~
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-suse
    image: "jomrr/suse-molecule:latest"
    command: ~
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: vscode-suse-tumbleweed
    image: "jomrr/suse-molecule:tumbleweed"
    command: ~
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: vscode-oracle7
    image: "jomrr/oracle-molecule:7"
    command: ~
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: vscode-oracle
    image: "jomrr/oracle-molecule:latest"
    command: ~
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: vscode-ubuntu1604
    image: "jomrr/ubuntu-molecule:16.04"
    command: ~
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: vscode-ubuntu1804
    image: "jomrr/ubuntu-molecule:18.04"
    command: ~
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: vscode-ubuntu
    image: "jomrr/ubuntu-molecule:latest"
    command: ~
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  log: True
  lint:
    name: ansible-lint
  playbooks:
    converge: ../shared/playbook.yml
  inventory:
    group_vars:
      all:
        vscode_enabled: True
scenario:
  name: all
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore"
  directory: ../tests
  options:
    v: True
    sudo: True
  lint:
    name: flake8
